trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  SFDX_CLI_VERSION: latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install --global sfdx-cli@$(SFDX_CLI_VERSION)
  displayName: 'Install Salesforce CLI'

- script: |
    sfdx --version
    sfdx plugins --core
  displayName: 'Verify Salesforce CLI installation'

- script: |
    echo $(SF_USERNAME)
    echo $(SF_SERVER_KEY) > server.key
    sfdx auth jwt grant --clientid $(SF_CLIENT_ID) --jwtkeyfile server.key --username $(SF_USERNAME) --instanceurl https://login.salesforce.com
  displayName: 'Authenticate to Salesforce'
  env:
    SF_CLIENT_ID: $(SF_CLIENT_ID)
    SF_USERNAME: $(SF_USERNAME)
    SF_SERVER_KEY: $(SF_SERVER_KEY)

- script: |
    sfdx force:source:convert -d deploy
  displayName: 'Convert source to metadata format'

- script: |
    sfdx force:mdapi:deploy -d deploy -u $(SF_USERNAME) -w 10
  displayName: 'Deploy to Salesforce org'
